### ISSUE TITLE
Issues when trying to build application

### ISSUE THREAD

**Issue by notorioustubze** [MobinurRahaman/ellipto-iptv#3]
root@debian:~/ellipto-iptv# yarn build
yarn run v1.22.19
$ react-scripts build
/bin/sh: 1: react-scripts: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@debian:~/ellipto-iptv# yarn start
yarn run v1.22.19
$ react-scripts start
/bin/sh: 1: react-scripts: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@debian:~/ellipto-iptv#

**Comment by MobinurRahaman** [comment]
@notorioustubze
> root@debian:~/ellipto-iptv# yarn build yarn run v1.22.19 $ react-scripts build /bin/sh: 1: react-scripts: not found error Command failed with exit code 127. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. root@debian:~/ellipto-iptv# yarn start yarn run v1.22.19 $ react-scripts start /bin/sh: 1: react-scripts: not found error Command failed with exit code 127. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. root@debian:~/ellipto-iptv#

Have you run `yarn install`? By doing so, it will install `react-scripts`.

**Comment by notorioustubze** [comment]
So to confirm, clone repository, cd to ellipto-iptv, then run Yarn install?Sent from my iPhoneOn 18 Oct 2023, at 09:26, Md Mobinur Rahaman ***@***.***> wrote:﻿

***@***.***:/ellipto-iptv# yarn build yarn run v1.22.19 $ react-scripts build /bin/sh: 1: react-scripts: not found error Command failed with exit code 127. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. ***@***.***:/ellipto-iptv# yarn start yarn run v1.22.19 $ react-scripts start /bin/sh: 1: react-scripts: not found error Command failed with exit code 127. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. ***@***.***:~/ellipto-iptv#

Have you run yarn install? By doing so, it will install react-scripts.

**Comment by MobinurRahaman** [comment]
> So to confirm, clone repository, cd to ellipto-iptv, then run Yarn install?Sent from my iPhoneOn 18 Oct 2023, at 09:26, Md Mobinur Rahaman ***@***.***> wrote:﻿ ***@***.***:/ellipto-iptv# yarn build yarn run v1.22.19 $ react-scripts build /bin/sh: 1: react-scripts: not found error Command failed with exit code 127. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. ***@***.***:/ellipto-iptv# yarn start yarn run v1.22.19 $ react-scripts start /bin/sh: 1: react-scripts: not found error Command failed with exit code 127. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. ***@***.***:~/ellipto-iptv# Have you run yarn install? By doing so, it will install react-scripts. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Yes. Are you able to build it?

**Comment by notorioustubze** [comment]
root@debian:~# cd ellipto-iptv
root@debian:~/ellipto-iptv# yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
root@debian:~/ellipto-iptv# 

Do I need to install react first?

**Comment by MobinurRahaman** [comment]
> root@debian:~# cd ellipto-iptv root@debian:~/ellipto-iptv# yarn install 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install' root@debian:~/ellipto-iptv#
> 
> Do I need to install react first?

You don't need to install React separately. The dependencies of this web app, including React and all other packages specified in the `package.json` file, will be automatically installed when you execute either the `npm install` or `yarn install` command.

It seems that Yarn is not currently installed on your system. To resolve this, you can globally install Yarn by using the command `npm install --global yarn`. After installing Yarn, you can proceed by running `yarn install` and then execute `yarn build` to successfully build this project.

**Comment by notorioustubze** [comment]
So followed your instructions and I get the following:
root@debian:~# npm install --global yarn

added 1 package in 1s
root@debian:~# git clone https://github.com/MobinurRahaman/ellipto-iptv.git
Cloning into 'ellipto-iptv'...
remote: Enumerating objects: 419, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 419 (delta 41), reused 37 (delta 26), pack-reused 356
Receiving objects: 100% (419/419), 305.59 KiB | 2.50 MiB/s, done.
Resolving deltas: 100% (256/256), done.
root@debian:~# cd ellipto-iptv
root@debian:~/ellipto-iptv# yarn install                                      
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@emotion/react > @emotion/babel-plugin@11.10.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > @vime/react@5.4.0" has incorrect peer dependency "react@^17.0.0".
warning " > @vime/react@5.4.0" has incorrect peer dependency "react-dom@^17.0.0".
warning " > dexie-react-hooks@1.1.1" has unmet peer dependency "@types/react@>=16".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "react-scripts > react-dev-utils > fork-ts-checker-webpack-plugin@6.5.2" has unmet peer dependency "typescript@>= 2.7".
warning "react-scripts > eslint-config-react-app > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
Done in 37.04s.
root@debian:~/ellipto-iptv# yarn build
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

<--- Last few GCs --->

[401:0x55f89f2a9580]    22365 ms: Scavenge (reduce) 249.5 (258.0) -> 249.3 (258.8) MB, 1.0 / 0.0 ms  (average mu = 0.637, current mu = 0.463) allocation failure; 
[401:0x55f89f2a9580]    22580 ms: Mark-sweep (reduce) 250.5 (259.0) -> 249.6 (259.5) MB, 212.8 / 0.0 ms  (average mu = 0.414, current mu = 0.052) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7f1e1d3f4a98 node::Abort() [/lib/x86_64-linux-gnu/libnode.so.108]
 2: 0x7f1e1d2f40ab  [/lib/x86_64-linux-gnu/libnode.so.108]
 3: 0x7f1e1d768e60 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.108]
 4: 0x7f1e1d76921b v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.108]
 5: 0x7f1e1d93a2f5  [/lib/x86_64-linux-gnu/libnode.so.108]
 6: 0x7f1e1d94f673 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.108]
 7: 0x7f1e1d92bcde v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.108]
 8: 0x7f1e1d92d074 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.108]
 9: 0x7f1e1d90dd7d v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/lib/x86_64-linux-gnu/libnode.so.108]
10: 0x7f1e1dce656a v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/lib/x86_64-linux-gnu/libnode.so.108]
11: 0x7f1e1d679b79  [/lib/x86_64-linux-gnu/libnode.so.108]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Thank you for your assistance with this.

**Comment by notorioustubze** [comment]
Cancel that It was my fault I hadn't allocated enough ram to the Container. Thank you so much for your assistance.
